language: php

php:
  - '5.6'

services:
  - mysql

before_script:
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - composer self-update
  - composer install --prefer-source
  - mysql -e 'create database if not exists microservices_test;'

script:
  - phpunit

after_success:
 - mkdir -p build/logs
 - cp tests/_output/coverage.xml build/logs/clover.xml
 - php vendor/bin/coveralls -v
 - bash <(curl -s https://codecov.io/bash)